---
name: Test-XML-Order
version: 0.04
author: ~
abstract: Compare the order of XML tags in perl tests
license: perl
requires:
  perl: 5.6.0
recommends:
  Test::Pod: 0
  Test::Pod::Coverage: 0
provides:
  Test::XML::Order:
    file: lib/Test/XML/Order.pm
    version: 0.04
generated_by: Module::Build version 0.26
